### ISSUE TITLE
[Request] Optional zoom for screenshots

### ISSUE THREAD

**Issue by AdrienDS** [HamzaEzzRa/Multishot#2]
Add an option to select a Zoom to take the screenshots:
- Zoom `[-] [ 100% ] [+]`
- Default increments for the zoom could mirror Chrome settings `⋮` menu -> Zoom

When taking screenshot with a non-100% zoom, scale the browser window accordingly so the effective captured resolution is still the requested resolution (1000px wide screenshot with 80% zoom should be done on a 800px wide window)

If possible, the zoom could be mentioned in the screenshots when it is not 100%.

This will make it possible to capture screenshots with a layout larger than the physical screen that the extension is ran on.

**Comment by HamzaEzzRa** [comment]
Added an option to individually control the zoom factor of each preset in the options page. The zoom increments match Chrome's.

This will affect the viewport similarly to what Chrome does when zooming (it won't affect the browser window itself, as that will be redundant with the option to create new presets).

It should be working in the current version (v0.4)
